apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voting-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Divyeshzb/newVotingApp
    targetRevision: HEAD
    path: helm-vote
  destination:
    server: https://kubernetes.default.svc
    namespace: ballot
  syncPolicy:
    syncOptions:    
    - CreateNamespace=true 
    automated: 
      prune: true
      selfHeal: true 