version: "3.9"
services:
  ballot:
    container_name: ballot
    image: zbio/ballot:latest
    ports:
      - "30040:8080"
  voter:
    container_name: voter
    image: zbio/voter:latest
    tty: true
    stdin_open: true
    ports: 
      - "30041:80"
    environment:
      REACT_APP_BALLOT_ENDPOINT:  "${ROOST_CLUSTER_IP}:30040"
      REACT_APP_EC_SERVER_ENDPOINT: "${ROOST_CLUSTER_IP}:30042"
    links:
      - ballot
      - ecserver
  ecserver:
    container_name: ecserver
    image: zbio/ecserver:latest
    ports: 
      - "30042:8081"
  election-commission:
    container_name: ec
    image: zbio/election-commission:latest
    tty: true
    stdin_open: true
    ports: 
      - "30043:80"
    environment:
      REACT_APP_EC_SERVER_ENDPOINT: "${ROOST_CLUSTER_IP}:30042"
    links:
      - ecserver
